
services:

  db:
    container_name: ${PROJECT_NAME}_db
    image: 'mysql:8.0.33'
    volumes:
      - './database/data:/var/lib/mysql'
    ports:
      - '3310:3306'
    networks:
      backend2:
        ipv4_address: 192.20.1.6
    environment:
      MYSQL_DATABASE: ojrdb
      MYSQL_ROOT_PASSWORD: Hondacr250
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "192.20.1.6"]
        timeout: 20s
        retries: 10

  web:
    container_name: ${PROJECT_NAME}_web
    build: .
    depends_on: 
      db:
        condition: service_healthy
    links:
      - db
    working_dir: /code
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8100:8000'
    expose:
      - '8000'
    networks:
      backend2:
        ipv4_address: 192.20.1.5

networks:
  backend2:
    driver: bridge
    ipam:
      config:
        - subnet: 192.20.1.0/24
